[package]
name = "rotsprite"
version = "0.1.4-alpha.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"
readme = "README.md"
repository = "https://github.com/tversteeg/rotsprite"
documentation = "https://docs.rs/rotsprite"
description = "Rotate sprites using the rotsprite algorithm"
keywords = ["game", "sprite", "blit", "rotation"]
categories = ["rendering", "game-engines"]

[dependencies]
multiversion = "0.5.0"
thiserror = "1.0.15"

[dev-dependencies]
blit = "0.5.12"
image = "0.23.3"
minifb = "0.16.0"
criterion = "0.3.1"
rand = "0.8.5"

[[bench]]
name = "rotsprite"
harness = false

[[bench]]
name = "scale2x"
harness = false

[[bench]]
name = "rotate"
harness = false
