name: Readme
on: push

jobs:
  # Generate the readme from lib.rs
  readme:
    name: Generate README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed for the amend
          fetch-depth: 2

      - uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-rdme
        run: cargo binstall cargo-rdme -y

      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Run cargo-rdme
        run: cargo rdme

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
